### ISSUE TITLE
Add top-level nav to BaseLayout

### ISSUE THREAD

**Issue by replygirl** [BSA-US/World-of-Jackson-Client#15]
In `layouts/BaseLayout.tsx`, add a top-level navigation component. Probably makes sense to create a separate component, e.g. `components/Nav.tsx`

There's no hard spec, but some starts at this are in [the Figma file](https://3.basecamp.com/4111666/buckets/15457593/documents/2575215067).

Notes:
- Needs to be responsive (drawer? tabs? something else?)
- Nav items aren't finalized—for now, create some dummy pages that import the BaseLayout

Useful docs:
- [Next.js routing](https://nextjs.org/docs/routing/introduction) (it's automatic)
- [next/link](https://nextjs.org/docs/api-reference/next/link)

**Comment by bradysheridan** [comment]
I can take this!
