### ISSUE TITLE
Rich/markup text in description

### ISSUE THREAD

**Issue by GrigoryGraborenko** [BSA-US/World-of-Jackson-Client#21]
Ability to insert html into the text for tour node descriptions. This will allow us to add quotes, links to further reading, images, all sorts of other nice stuff. 
Try to avoid react's dangerouslySetInnerHTML - there might be security concerns around creating script tags.

**Comment by desmukh** [comment]
I'll take a crack at this if no one else is on it? I was thinking of implementing either the [Interweave react plugin](https://github.com/milesj/interweave), or the [react-markdown plugin](https://github.com/rexxars/react-markdown) (if we want to use markdown rather than plain html)

Let me know if anyone has a better/different solution in mind, or any other advice?

**Comment by GrigoryGraborenko** [comment]
Hey, sorry, should have replied earlier! We actually partially solved this already - we used https://www.npmjs.com/package/sanitize-html in conjunction with react's dangerouslySetInnerHTML

**Comment by melnyczuk** [comment]
Hi 👋  Is this still open? I'm happy to pick it up!
Using `dangerouslySetInnerHTML` poses an XSS security vulnerability, so we should err against it.

**Comment by GrigoryGraborenko** [comment]
Thanks! If you can find a better library for this, please, go ahead and try and solve this without dangerouslySetInnerHTML. I was hoping that using the sanitation lib, which strips out <script> tags, would be sufficient, but if it's not, we should do better.

**Comment by zspencer** [comment]
I have heard good things about using [mdxjs](https://mdxjs.com/getting-started) for rendering react components from Markdown.

**Comment by melnyczuk** [comment]
I'll have a go, and try to open a PR as soon as I can 👍

**Comment by melnyczuk** [comment]
Has anyone ever tried this? https://github.com/rexxars/react-markdown
Will also have a look at mdx.js

**Comment by melnyczuk** [comment]
> I have heard good things about using [mdxjs](https://mdxjs.com/getting-started) for rendering react components from Markdown.

This looks really good

**Comment by GrigoryGraborenko** [comment]
Turns out contentful had a nice way of doing this
