### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by GrigoryGraborenko** [BSA-US/World-of-Jackson-Client#25]
On mobile especially, have a hamburger menu in the top right that activates a full screen menu overlay.

**Comment by sparklestheunicorn** [comment]
This seems like it is a sub-task of [Issue 15](https://github.com/BSA-US/world-of-jackson/issues/15)

**Comment by sparklestheunicorn** [comment]
My [latest merge](https://github.com/BSA-US/world-of-jackson/pull/64) should take care of this. I'm closing the issue.
