### ISSUE TITLE
GeoJSON data model

### ISSUE THREAD

**Issue by sorcerix** [BSA-US/World-of-Jackson-Client#3]
to be able to highlight particular buildings and give them each unique events, we will need to create a custom data model through which we can render and update them. 

This data model should make each building easy to find, and allow us to render unique 3d models of them

We are currently working with GeoJSON to render buildings in MapBox-GL

see more on geojson here:
https://geojson.org/

**Comment by replygirl** [comment]
relates to #9

**Comment by replygirl** [comment]
closing
