### ISSUE TITLE
Switch out React with Preact?

### ISSUE THREAD

**Issue by sorcerix** [BSA-US/World-of-Jackson-Client#45]
In an attempt to be more lightweight and have a smaller bundle size, I was thinking w look into preact as an almost identical alternative to react

https://preactjs.com/

For the most part, it has the same functionality as react, our tradeoff would be losing some of the more advanced, niche functionality of react, as well as the synthetic event system, which may be challenging to use with our non react map anyway

**Comment by replygirl** [comment]
[Found a demo repo!](https://github.com/developit/nextjs-preact-demo)
