### ISSUE TITLE
Write typography styles and create text preview page

### ISSUE THREAD

**Issue by bradysheridan** [BSA-US/World-of-Jackson-Client#47]
It would be useful to start a master sheet of responsive typography styles as well as a behind-the-scenes page that renders all headers, paragraphs, etc., so that we can tweak on the fly and see how text elements look relative to one another. This will decrease amount of time spent on styles for future components, ensure visual consistency across the site and reduce style fragmentation throughout repo.

- [x] Create typography style sheet
- [x] Set up font sizes for various elements using relative units (to start, h1-h6 and p)
- [x] Ensure font sizes are responsive
- [x] Create text preview page (pages/typography?) comparing text elements with dummy text

**Comment by sparklestheunicorn** [comment]
I am happy to design and implement an initial brand guidelines based on the colors and fonts from `https://cooperationjackson.org/`. Do we have any design folks or existing guides? Design isn't my primary skill set but I can make something decent to get us started.
