### ISSUE TITLE
Test deck.gl with typescript bindings

### ISSUE THREAD

**Issue by sorcerix** [BSA-US/World-of-Jackson-Client#5]
There has been a budding interest in using deck.gl for rendering 3D polygons and basic map styling. However, we have to find the proper typescript bindings in order to make this happen. Some background:

Relevant github issue: https://github.com/uber/deck.gl/issues/1103

Current prototype created by Tyler:
https://codesandbox.io/s/inspiring-leakey-hokei

AC:
1. Convert Tyler's code to typescript with bindings for deck.gl
2. Be able to call a function from the top level component with an array of building id's and have those buildings highlight in the map
3. If a building is clicked, callback a function in the top level component with the relevant building id

This can be a standalone project and doesn't need to be a branch, but deck.gl has excellent shading features such that we think it is worth the research

**Comment by sorcerix** [comment]
UPDATE: we have been able to make deck.gl work with mapbox.gl, but we still need to make sure that our shadows and polygons render smoothly. We still want those typescript bindings too!

**Comment by GrigoryGraborenko** [comment]
Research suggests there isn't any decent off-the-shelf bindings for deck.gl at the moment. Creating our own would be far too much effort for too little value.
