### ISSUE TITLE
Rename `master` to `prod`

### ISSUE THREAD

**Issue by replygirl** [BSA-US/World-of-Jackson-Client#56]
Requires admin access to the repo

- [ ] Create `prod` branch by branching off `dev`
- [ ] Change `master` branch protection pattern to `prod`
- [ ] Change repo's default branch to `prod`
- [ ] Delete `master`
- [ ] Replace any references to `master` in docs with `prod`

**Comment by dmitrizagidulin** [comment]
+1. Would it make sense to rename the `master` branch to `main` (instead of `prod`), to match [where GitHub itself is moving](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/)?
