### ISSUE TITLE
Integrate styling library/framework.

### ISSUE THREAD

**Issue by sorcerix** [BSA-US/World-of-Jackson-Client#7]
Recommend using this one, but other suggestions welcome:
https://styled-components.com/
Experience has shown it's good for fine tuning component look/feel, making them robust against future changes

Take a look here for our working design
![WOJ_working design one](https://user-images.githubusercontent.com/59036028/78945094-73cccb00-7a8d-11ea-9bcc-8f8f16100001.PNG)

AC:
1. Use styling library to make the tour nodes on the left look alright
2. make the buttons stand out and easy to use

**Comment by gristleism** [comment]
@sorcerix happy to take a crack at this, was wondering based on the current repository state if I should branch off of `skeleton`, or `skeleton-no-wrapper`? Or I see they both seem to splinter off at commit [dc77259](https://github.com/BSA-US/world-of-jackson/commit/dc77259b342f65516d4a9827fe006275d5a387f4), could maybe start there?

**Comment by GrigoryGraborenko** [comment]
Ideally skeleton-no-wrapper, latest commit. We're probably gonna abandon skeleton, since deck.gl is almost integrated succesfully.

**Comment by sorcerix** [comment]
@gristleism awesome! Let us know if you have any questions. Also if you want to do any further design work please let us know

**Comment by GrigoryGraborenko** [comment]
This has been finished.
