### ISSUE TITLE
Solidify Yarn as the package manager

### ISSUE THREAD

**Issue by bnns** [BSA-US/World-of-Jackson-Client#74]
We shouldn't have both a `package-lock.json` and a `yarn.lock` - since docs say to use Yarn, we should stick with that to avoid inconsistent deps.

**Comment by dmitrizagidulin** [comment]
+1 to picking just one. I do want to ask - would the team consider _not_ using a `.lock` file at all? I completely understand the arguments for using it. But in the dozens of projects that I've worked on that used it, it's honestly caused more developer confusion and heart-ache than the problems it fixed or prevented.

**Comment by bnns** [comment]
that's an interesting idea - since Yarn autogenerates the lockfile (unless you run it as `yarn install --pure-lockfile`), we would likely need to add `yarn.lock` to the `.gitignore` - so effectively everyone would have their own lockfile but it would never go to the repo - I'm up for this if we get at least 3 or 4 more devs to agree

**Comment by patcon** [comment]
Sorry to drive-by (no offense with the :-1:) but my hot-take is that missing lockfiles hurt newcomers to a project (fresh installs), whereas challenges of present lockfiles are encountered by experienced contributors (rebasing, merging). I'd humbly suggest first timer experience be prioritized as a dev philosophy :)

Alternatively, if decide to gitignore, would suggest adding a postinstall (or githook via husky) to delete lockfiles each time for everyone, so experienced folks are hitting any pain new ppl would. (I'm guessing the practice will seem less fun after awhile of trying that tbh)

Anyhow, y'all are awesome regardless
