### ISSUE TITLE
Add content hashes to static file serving from Next.js

### ISSUE THREAD

**Issue by sorcerix** [BSA-US/World-of-Jackson-Client#8]
Currently we have to do hard reloads when testing updates, and when refreshing the page to resolve many caching oriented errors, and hope to enable cache busting to prevent this

**Comment by emilyhorsman** [comment]
Going to test `next-optimized-images` out to add content hashes: https://github.com/cyrilwanner/next-optimized-images

**Comment by sorcerix** [comment]
awesome! Let us know if we can help with anything @emilyhorsman

**Comment by emilyhorsman** [comment]
Looks like the existing Next.js configuration already hashes CSS/JS/etc. Closing this. Worth exploring again if we have image assets later.
